# Generated by Django 5.2.7 on 2025-10-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paliwko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_paliwa', models.CharField(max_length=255)),
                ('cena', models.IntegerField(max_length=32)),
            ],
        ),
    ]
