# Generated by Django 5.2.7 on 2025-10-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliwkoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paliwko',
            name='cena',
            field=models.IntegerField(),
        ),
    ]
