# Generated by Django 5.2.7 on 2025-10-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliwkoapp', '0002_alter_paliwko_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paliwko',
            name='cena',
            field=models.FloatField(),
        ),
    ]
