# Generated by Django 5.2.7 on 2025-10-27 07:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samochody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('rocznik', models.IntegerField()),
                ('kolor', models.CharField(max_length=200)),
                ('stan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
                ('data_zamowienia', models.DateTimeField(default=datetime.datetime(2025, 10, 27, 8, 37, 40, 856915))),
                ('id_samochodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komisapp.samochody')),
            ],
        ),
    ]
