# Generated by Django 5.2.7 on 2025-10-27 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienia',
            name='data_zamowienia',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 8, 37, 53, 424081)),
        ),
    ]
