# Generated by Django 5.2.7 on 2025-10-27 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komisapp', '0002_alter_zamowienia_data_zamowienia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienia',
            name='data_zamowienia',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
