# Generated by Django 5.1.4 on 2024-12-18 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prowadzacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('klasa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spotkania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('prowadzacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apka.prowadzacy')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apka.uczen')),
            ],
        ),
    ]
