# Generated by Django 5.1.6 on 2025-02-18 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('telefon', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ogloszenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.PositiveSmallIntegerField()),
                ('podkategoria', models.PositiveSmallIntegerField()),
                ('tytul', models.CharField(max_length=100)),
                ('tresc', models.TextField()),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_app.uzytkownik')),
            ],
        ),
    ]
