# Generated by Django 5.2.7 on 2025-10-06 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Potrawy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rodzina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grzyby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('potoczna', models.CharField(max_length=100)),
                ('jadalny', models.CharField(max_length=100)),
                ('miesiac_zbierania', models.CharField(max_length=100)),
                ('potrawy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grzybyapp.potrawy')),
                ('rodzina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grzybyapp.rodzina')),
            ],
        ),
    ]
