# Generated by Django 5.2.7 on 2025-10-20 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('stanowisko', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('cena', models.IntegerField()),
                ('kadra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautyapp.kadra')),
            ],
        ),
    ]
